### ISSUE TITLE
Invalid WebhookOptions returned

### ISSUE THREAD

**Issue by woodspire** [CometBackup/comet-php-sdk#1]
On a server where WebhookOptions have never been configured, the call to AdminMetaWebhookOptionsGet return 'null', instead of returning an empty dictionnary : {}

This make this library crash in file vendor/cometbackup/comet-php-sdk/Comet/AdminMetaWebhookOptionsGetRequest.php on line 87 because the result of json_decode is not an array of \stdClass.

Setting {} via AdminMetaWebhookOptionsSet works and after that, returns correctly the empty dictionnary.

**Comment by mason-cometbackup** [comment]
Thank you very much for this informative and helpful bug report. I can confirm the issue.

The issue affects Comet Server 20.8.1 and earlier; and the Comet PHP SDK v3.6.0 and earlier.

We will fix the issue in the next version of Comet Server (probably 20.8.2 on Monday 7th) and will also apply mitigations in this PHP SDK so that the issue will not occur on older versions of Comet Server.

**Comment by mason-cometbackup** [comment]
I've tagged a `v3.7.0` release with this fix and also the fix for #2 - please upgrade your Composer package!

Thanks again for your contribution here, you've really helped improve the SDK for everyone.
