### ISSUE TITLE
support guzzle 7

### ISSUE THREAD

**Issue by woodspire** [CometBackup/comet-php-sdk#5]
Laravel 8 require guzzle 7.0.1 so currently, this package cannot be used with it.
You still might want to support guzzle 6 too, because the php version for guzzle 7  is >=7.2

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by ersin-comet** [comment]
We would like to support guzzle 6 and 7 for the SDK, I've tested this out locally and it doesn't seem to require any code change to get tests to pass on version 7 of guzzle.

The minimum version of PHP we will need to support is 7.0 however, as we want to keep consistent with the php package shipped with current LTS version debian.

We are happy to accept PR's for this issue, and want to keep the SDK up to date so that integration is easier for people using the comet server SDK.

**Comment by mason-cometbackup** [comment]
Fixed by #7 :tada:
